version: 2.1 # CircleCIのバージョン
jobs: # ジョブという単位で構成、デフォルトでbuildという名前のジョブが実行される
  build: # 実行環境や実行されるステップで構成
    docker:
      - image: circleci/node:10
        # デフォルトでUTC、タイムゾーンを意識しない場合は不要
        environment:
          TZ: Asia/Tokyo
    steps: # 実行するコマンド、上から順に実行される
      # - run: でシェルコマンドを実行
      - checkout # Gitリポジトリからソースをチェックアウト
      - restore_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache: # ブランチ名と`package-lock.json`のハッシュをキーとしてキャッシュ
          key: npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm # npm ci の場合node_modules/以下は一度削除されるので
      - run: npm run test:unit
      - run: npm run build
      - run: echo "run deploy script"
